import './globals.css'
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Inter } from 'next/font/google'
import { Navbar } from '../components/Navbar/Navbar'
import Footer from '../components/Footer/Footer'

import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Access to Vintage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        <SpeedInsights/>
      </body>
    </html>
  )
}
